### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/christofffinio#2]
@gehalber Geoff, can you clarify for me what I'm seeing on the About page? (And apologies if you already wrote this somewhere...)

Is there, like, an expansion thing happening between the 4th and 5th paragraphs? Is that why they're shown in separate layouts in the InDesign?

If so, what's the trigger, there?

**Comment by gehalber** [comment]
@halfempty @keningzhu Right, there's just a lot of content so we didn't want to overwhelm. There's a Read More button which would load the content below.

<img width="998" alt="screen shot 2017-10-10 at 10 44 33 am" src="https://user-images.githubusercontent.com/6076488/31392787-21f0ed34-ada8-11e7-927e-5a3174f66cf0.png">

**Comment by halfempty** [comment]
@gehalber Oh! My file, called "CF_Design_05" doesn't have the "Read More." Is there a later version I should reference? (NBD on the button itself, I just don't want to miss any other changes)

**Comment by gehalber** [comment]
@halfempty Weird. It was hidden in the text box. I just resaved for you. No other changes should have been made to the file.
